export const HISTORY_TYPE = {
    ORDER: "ORDER",
    VIEWED_PRODUCT: "VIEWED_PRODUCT",
    CHANGE_PASSWORD: "CHANGE_PASSWORD",
    COMMENT: "COMMENT",
    RATING: "RATING",
    LOG_TIME: "LOG_TIME",
}

export const TIME_FORMAT = "YYYY-MM-DDTHH:mm:ssZ[Z]"